version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      gh-actions:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    groups:
      pip-dependencies:
        patterns: ["*"]
