"""DSM 6 SYNO.Core.System data."""

DSM_6_CORE_SYSTEM_DS918_PLUS = {
    "data": {
        "cpu_clock_speed": 1500,
        "cpu_cores": "4",
        "cpu_family": "Celeron",
        "cpu_series": "J3455",
        "cpu_vendor": "INTEL",
        "enabled_ntp": True,
        "firmware_date": "2020/07/08",
        "firmware_ver": "DSM 6.2.3-25426 Update 2",
        "model": "DS918+",
        "ntp_server": "time.google.com",
        "ram_size": 4096,
        "sata_dev": [],
        "serial": "1920PDN001501",
        "support_esata": "yes",
        "sys_temp": 40,
        "sys_tempwarn": False,
        "systempwarn": False,
        "temperature_warning": False,
        "time": "2020-10-19 23:33:52",
        "time_zone": "Brussels",
        "time_zone_desc": "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris",
        "up_time": "75:12:9",
        "usb_dev": [
            {
                "cls": "hub",
                "pid": "0612",
                "producer": "Genesys Logic, Inc.",
                "product": "Hub",
                "rev": "92.23",
                "vid": "05e3",
            },
            {
                "cls": "other",
                "pid": "1790",
                "producer": "ASIX Electronics Corp.",
                "product": "AX88179 Gigabit Ethernet",
                "rev": "1.00",
                "vid": "0b95",
            },
            {
                "cls": "hub",
                "pid": "0610",
                "producer": "Genesys Logic, Inc.",
                "product": "4-port hub",
                "rev": "92.23",
                "vid": "05e3",
            },
            {
                "cls": "other",
                "pid": "0200",
                "producer": "Sigma Designs, Inc.",
                "product": "Aeotec Z-Stick Gen5 (ZW090) - UZB",
                "rev": "0.00",
                "vid": "0658",
            },
            {
                "cls": "ups",
                "pid": "0002",
                "producer": "American Power Conversion",
                "product": "Uninterruptible Power Supply",
                "rev": "1.06",
                "vid": "051d",
            },
        ],
    },
    "success": True,
}

DSM_6_CORE_SYSTEM_DS218_PLAY = {
    "data": {
        "cpu_clock_speed": 1400,
        "cpu_cores": "4",
        "cpu_family": "RTD1296",
        "cpu_series": "SoC",
        "cpu_vendor": "Realtek",
        "enabled_ntp": True,
        "firmware_date": "2020/07/14",
        "firmware_ver": "DSM 6.2.3-25426 Update 2",
        "model": "DS218play",
        "ntp_server": "pool.ntp.org",
        "ram_size": 1024,
        "serial": "123456abcdefg",
        "support_esata": "no",
        "sys_temp": 40,
        "sys_tempwarn": False,
        "systempwarn": False,
        "temperature_warning": False,
        "time": "2020-10-16 20:26:58",
        "time_zone": "Amsterdam",
        "time_zone_desc": "(GMT+01:00) Amsterdam, Berlin, Rome, Stockholm, Vienna",
        "up_time": "289:31:54",
        "usb_dev": [
            {
                "cls": "disk",
                "pid": "2621",
                "producer": "Western Digital Technologies, Inc.",
                "product": "Elements 2621",
                "rev": "10.26",
                "vid": "1058",
            }
        ],
    },
    "success": True,
}

DSM_6_CORE_SYSTEM_STORAGE = {
    "data": {
        "hdd_info": [
            {
                "action": {
                    "alert": True,
                    "allow_binding": True,
                    "allow_ma_create": True,
                    "notification": False,
                    "selectable": True,
                    "show_lifetime_chart": True,
                },
                "action_status": {"action_name": "idle", "action_progress": ""},
                "action_status_category": "processing",
                "action_status_key": "idle",
                "adv_progress": "",
                "adv_status": "not_support",
                "allocation_role": "reuse_3",
                "below_remain_life_mail_notify_thr": False,
                "below_remain_life_show_thr": False,
                "below_remain_life_thr": False,
                "compatibility": "not_in_support",
                "container": {
                    "order": 0,
                    "str": "DS923+",
                    "supportPwrBtnDisable": False,
                    "type": "internal",
                },
                "container_id": 0,
                "device": "/dev/sata1",
                "disable_secera": False,
                "diskType": "SATA",
                "disk_code": "",
                "disk_location": "Main",
                "drive_status_category": "health",
                "drive_status_key": "normal",
                "erase_time": 318,
                "firm": "CV23",
                "firmware_status": "-",
                "has_system": True,
                "hide_info": [],
                "i18nNamingInfo": '["dsm:volume:volume_disk"," ","1"]',
                "id": "sata1",
                "ihm_testing": False,
                "is4Kn": False,
                "isSsd": False,
                "isSynoDrive": False,
                "isSynoPartition": True,
                "is_bundle_ssd": False,
                "is_erasing": False,
                "longName": "Drive 1",
                "m2_pool_support": False,
                "model": "ST3000VX000-1CU166",
                "name": "Drive 1",
                "num_id": 1,
                "order": 1,
                "overview_status": "normal",
                "pciSlot": -1,
                "perf_testing": False,
                "portType": "normal",
                "remain_life": {"trustable": True, "value": -1},
                "remain_life_danger": False,
                "remote_info": {"compatibility": "disabled", "unc": 0},
                "sb_days_left": 0,
                "sb_days_left_below_show_thres": False,
                "sb_days_left_critical": False,
                "sb_days_left_warning": False,
                "serial": "W1F5ESED",
                "size_total": "3000592982016",
                "slot_id": 1,
                "smart_progress": "",
                "smart_status": "normal",
                "smart_test_limit": 0,
                "smart_test_support": True,
                "smart_testing": False,
                "ssd_unhealth_reason": "none",
                "status": "normal",
                "summary_status_category": "health",
                "summary_status_key": "normal",
                "temp": 38,
                "testing_progress": "",
                "testing_type": "idle",
                "tray_status": "join",
                "ui_serial": "W1F5ESED",
                "unc": 0,
                "used_by": "reuse_3",
                "vendor": "Seagate",
                "wcache_force_off": False,
                "wcache_force_on": False,
                "wdda_support": False,
            },
            {
                "action": {
                    "alert": True,
                    "allow_binding": True,
                    "allow_ma_create": True,
                    "notification": False,
                    "selectable": True,
                    "show_lifetime_chart": True,
                },
                "action_status": {"action_name": "idle", "action_progress": ""},
                "action_status_category": "processing",
                "action_status_key": "idle",
                "adv_progress": "",
                "adv_status": "not_support",
                "allocation_role": "reuse_1",
                "below_remain_life_mail_notify_thr": False,
                "below_remain_life_show_thr": False,
                "below_remain_life_thr": False,
                "compatibility": "not_in_support",
                "container": {
                    "order": 0,
                    "str": "DS923+",
                    "supportPwrBtnDisable": False,
                    "type": "internal",
                },
                "container_id": 0,
                "device": "/dev/sata2",
                "disable_secera": False,
                "diskType": "SATA",
                "disk_code": "",
                "disk_location": "Main",
                "drive_status_category": "health",
                "drive_status_key": "normal",
                "erase_time": 944,
                "firm": "KQ0C1L",
                "firmware_status": "-",
                "has_system": True,
                "hide_info": [],
                "i18nNamingInfo": '["dsm:volume:volume_disk"," ","2"]',
                "id": "sata2",
                "ihm_testing": False,
                "is4Kn": False,
                "isSsd": False,
                "isSynoDrive": False,
                "isSynoPartition": True,
                "is_bundle_ssd": False,
                "is_erasing": False,
                "longName": "Drive 2",
                "m2_pool_support": False,
                "model": "DS60HKVS-VX1",
                "name": "Drive 2",
                "num_id": 2,
                "order": 2,
                "overview_status": "normal",
                "pciSlot": -1,
                "perf_testing": False,
                "portType": "normal",
                "remain_life": {"trustable": True, "value": -1},
                "remain_life_danger": False,
                "remote_info": {"compatibility": "disabled", "unc": 0},
                "sb_days_left": 0,
                "sb_days_left_below_show_thres": False,
                "sb_days_left_critical": False,
                "sb_days_left_warning": False,
                "serial": "95G2S5ZGSSUL",
                "size_total": "6001175126016",
                "slot_id": 2,
                "smart_progress": "",
                "smart_status": "normal",
                "smart_test_limit": 0,
                "smart_test_support": True,
                "smart_testing": False,
                "ssd_unhealth_reason": "none",
                "status": "normal",
                "summary_status_category": "health",
                "summary_status_key": "normal",
                "temp": 35,
                "testing_progress": "",
                "testing_type": "idle",
                "tray_status": "join",
                "ui_serial": "95G2S5ZGSSUL",
                "unc": 0,
                "used_by": "reuse_1",
                "vendor": "HIKVISIO",
                "wcache_force_off": False,
                "wcache_force_on": False,
                "wdda_support": False,
            },
            {
                "action": {
                    "alert": True,
                    "allow_binding": True,
                    "allow_ma_create": True,
                    "notification": False,
                    "selectable": True,
                    "show_lifetime_chart": True,
                },
                "action_status": {"action_name": "idle", "action_progress": ""},
                "action_status_category": "processing",
                "action_status_key": "idle",
                "adv_progress": "",
                "adv_status": "not_support",
                "allocation_role": "reuse_1",
                "below_remain_life_mail_notify_thr": False,
                "below_remain_life_show_thr": False,
                "below_remain_life_thr": False,
                "compatibility": "not_in_support",
                "container": {
                    "order": 0,
                    "str": "DS923+",
                    "supportPwrBtnDisable": False,
                    "type": "internal",
                },
                "container_id": 0,
                "device": "/dev/sata3",
                "disable_secera": False,
                "diskType": "SATA",
                "disk_code": "",
                "disk_location": "Main",
                "drive_status_category": "health",
                "drive_status_key": "normal",
                "erase_time": 960,
                "firm": "KQ0C1L",
                "firmware_status": "-",
                "has_system": True,
                "hide_info": [],
                "i18nNamingInfo": '["dsm:volume:volume_disk"," ","3"]',
                "id": "sata3",
                "ihm_testing": False,
                "is4Kn": False,
                "isSsd": False,
                "isSynoDrive": False,
                "isSynoPartition": True,
                "is_bundle_ssd": False,
                "is_erasing": False,
                "longName": "Drive 3",
                "m2_pool_support": False,
                "model": "DS60HKVS-VX1",
                "name": "Drive 3",
                "num_id": 3,
                "order": 3,
                "overview_status": "normal",
                "pciSlot": -1,
                "perf_testing": False,
                "portType": "normal",
                "remain_life": {"trustable": True, "value": -1},
                "remain_life_danger": False,
                "remote_info": {"compatibility": "disabled", "unc": 0},
                "sb_days_left": 0,
                "sb_days_left_below_show_thres": False,
                "sb_days_left_critical": False,
                "sb_days_left_warning": False,
                "serial": "95G2S600SSUL",
                "size_total": "6001175126016",
                "slot_id": 3,
                "smart_progress": "",
                "smart_status": "normal",
                "smart_test_limit": 0,
                "smart_test_support": True,
                "smart_testing": False,
                "ssd_unhealth_reason": "none",
                "status": "normal",
                "summary_status_category": "health",
                "summary_status_key": "normal",
                "temp": 35,
                "testing_progress": "",
                "testing_type": "idle",
                "tray_status": "join",
                "ui_serial": "95G2S600SSUL",
                "unc": 0,
                "used_by": "reuse_1",
                "vendor": "HIKVISIO",
                "wcache_force_off": False,
                "wcache_force_on": False,
                "wdda_support": False,
            },
            {
                "action": {
                    "alert": True,
                    "allow_binding": True,
                    "allow_ma_create": True,
                    "notification": False,
                    "selectable": True,
                    "show_lifetime_chart": True,
                },
                "action_status": {"action_name": "idle", "action_progress": ""},
                "action_status_category": "processing",
                "action_status_key": "idle",
                "adv_progress": "",
                "adv_status": "not_support",
                "allocation_role": "reuse_1",
                "below_remain_life_mail_notify_thr": False,
                "below_remain_life_show_thr": False,
                "below_remain_life_thr": False,
                "compatibility": "not_in_support",
                "container": {
                    "order": 0,
                    "str": "DS923+",
                    "supportPwrBtnDisable": False,
                    "type": "internal",
                },
                "container_id": 0,
                "device": "/dev/sata4",
                "disable_secera": False,
                "diskType": "SATA",
                "disk_code": "",
                "disk_location": "Main",
                "drive_status_category": "health",
                "drive_status_key": "normal",
                "erase_time": 958,
                "firm": "KQ0C1L",
                "firmware_status": "-",
                "has_system": True,
                "hide_info": [],
                "i18nNamingInfo": '["dsm:volume:volume_disk"," ","4"]',
                "id": "sata4",
                "ihm_testing": False,
                "is4Kn": False,
                "isSsd": False,
                "isSynoDrive": False,
                "isSynoPartition": True,
                "is_bundle_ssd": False,
                "is_erasing": False,
                "longName": "Drive 4",
                "m2_pool_support": False,
                "model": "DS60HKVS-VX1",
                "name": "Drive 4",
                "num_id": 4,
                "order": 4,
                "overview_status": "normal",
                "pciSlot": -1,
                "perf_testing": False,
                "portType": "normal",
                "remain_life": {"trustable": True, "value": -1},
                "remain_life_danger": False,
                "remote_info": {"compatibility": "disabled", "unc": 0},
                "sb_days_left": 0,
                "sb_days_left_below_show_thres": False,
                "sb_days_left_critical": False,
                "sb_days_left_warning": False,
                "serial": "95G2S5ZRSSUL",
                "size_total": "6001175126016",
                "slot_id": 4,
                "smart_progress": "",
                "smart_status": "normal",
                "smart_test_limit": 0,
                "smart_test_support": True,
                "smart_testing": False,
                "ssd_unhealth_reason": "none",
                "status": "normal",
                "summary_status_category": "health",
                "summary_status_key": "normal",
                "temp": 35,
                "testing_progress": "",
                "testing_type": "idle",
                "tray_status": "join",
                "ui_serial": "95G2S5ZRSSUL",
                "unc": 0,
                "used_by": "reuse_1",
                "vendor": "HIKVISIO",
                "wcache_force_off": False,
                "wcache_force_on": False,
                "wdda_support": False,
            },
            {
                "action": {
                    "alert": True,
                    "allow_binding": True,
                    "allow_ma_create": True,
                    "notification": False,
                    "selectable": True,
                    "show_lifetime_chart": True,
                },
                "action_status": {"action_name": "idle", "action_progress": ""},
                "action_status_category": "processing",
                "action_status_key": "idle",
                "adv_progress": "",
                "adv_status": "not_support",
                "allocation_role": "reuse_2",
                "below_remain_life_mail_notify_thr": False,
                "below_remain_life_show_thr": False,
                "below_remain_life_thr": False,
                "compatibility": "not_in_support",
                "container": {
                    "order": 0,
                    "str": "DS923+",
                    "supportPwrBtnDisable": False,
                    "type": "internal",
                },
                "container_id": 2000,
                "device": "/dev/nvme0n1",
                "disable_secera": False,
                "diskType": "M.2 NVMe",
                "disk_code": "",
                "disk_location": "Native M.2",
                "drive_status_category": "health",
                "drive_status_key": "normal",
                "erase_time": 1,
                "firm": "2B2QEXM1",
                "firmware_status": "-",
                "has_system": False,
                "hide_info": [],
                "i18nNamingInfo": '["dsm:volume:volume_m2_device"," ","1"]',
                "id": "nvme0n1",
                "ihm_testing": False,
                "is4Kn": False,
                "isSsd": True,
                "isSynoDrive": False,
                "isSynoPartition": True,
                "is_bundle_ssd": False,
                "is_erasing": False,
                "longName": "Drive M.2 1",
                "m2_pool_support": False,
                "model": "Samsung SSD 970 EVO Plus 500GB",
                "name": "Drive M.2 1",
                "num_id": 1,
                "order": 1,
                "overview_status": "normal",
                "pciSlot": 0,
                "perf_testing": False,
                "portType": "cache",
                "remain_life": {"trustable": True, "value": 100},
                "remain_life_danger": False,
                "remote_info": {"compatibility": "disabled", "unc": 0},
                "sb_days_left": 0,
                "sb_days_left_below_show_thres": False,
                "sb_days_left_critical": False,
                "sb_days_left_warning": False,
                "serial": "S4EVNX0W541182V",
                "size_total": "500107862016",
                "slot_id": 1,
                "smart_progress": "",
                "smart_status": "normal",
                "smart_test_limit": 0,
                "smart_test_support": False,
                "smart_testing": False,
                "ssd_unhealth_reason": "none",
                "status": "normal",
                "summary_status_category": "health",
                "summary_status_key": "normal",
                "temp": 42,
                "testing_progress": "",
                "testing_type": "idle",
                "tray_status": "not join",
                "ui_serial": "S4EVNX0W541182V",
                "unc": -1,
                "used_by": "reuse_2",
                "vendor": "Samsung",
                "wcache_force_off": False,
                "wcache_force_on": False,
                "wdda_support": False,
            },
        ],
        "vol_info": [
            {
                "desc": "",
                "inode_free": "0",
                "inode_total": "0",
                "is_encrypted": False,
                "name": "volume_3",
                "status": "normal",
                "total_size": "2869725351936",
                "used_size": "199668277248",
                "vol_desc": "",
                "volume": "volume_3",
            },
            {
                "desc": "",
                "inode_free": "0",
                "inode_total": "0",
                "is_encrypted": False,
                "name": "volume_1",
                "status": "normal",
                "total_size": "11500548030464",
                "used_size": "5691705286656",
                "vol_desc": "mainVol",
                "volume": "volume_1",
            },
            {
                "desc": "",
                "inode_free": "0",
                "inode_total": "0",
                "is_encrypted": False,
                "name": "volume_2",
                "status": "normal",
                "total_size": "469010432000",
                "used_size": "156814848000",
                "vol_desc": "ssdVol",
                "volume": "volume_2",
            },
        ],
    },
    "success": True,
}
